/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "one_hot_detect.v:1" *)
module one_hot_detect(data_in, is_one_hot);
  wire 00;
  wire 01;
  wire 02;
  wire 03;
  wire 04;
  (* src = "one_hot_detect.v:2" *)
  input [2:0] data_in;
  (* src = "one_hot_detect.v:3" *)
  output is_one_hot;
  NAND 05 (
    .A(data_in[1]),
    .B(data_in[2]),
    .Y(01)
  );
  NOR 06 (
    .A(data_in[0]),
    .B(00),
    .Y(02)
  );
  NAND 07 (
    .A(01),
    .B(02),
    .Y(03)
  );
  NAND 08 (
    .A(data_in[0]),
    .B(00),
    .Y(04)
  );
  NAND 09 (
    .A(03),
    .B(04),
    .Y(is_one_hot)
  );
  NOR 10 (
    .A(data_in[1]),
    .B(data_in[2]),
    .Y(00)
  );
endmodule